<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\URL;



$user = Data::get('user');
?>



<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            background-color: white;
        }

        * {
            box-sizing: border-box;
        }

        /* Add padding to containers */
        .container {
            padding: 16px;
            background-color: white;
        }

        /* Full-width input fields */
        input[type=text], input[type=password] {
            width: 100%;
            padding: 15px;
            margin: 5px 0 22px 0;
            display: inline-block;
            border: none;
            background: #f1f1f1;
        }

        input[type=text]:focus, input[type=password]:focus {
            background-color: #ddd;
            outline: none;
        }

        /* Overwrite default styles of hr */
        hr {
            border: 1px solid #f1f1f1;
            margin-bottom: 25px;
        }

        /* Set a style for the submit button */
        .registerbtn {
            background-color: #4CAF50;
            color: white;
            padding: 16px 20px;
            margin: 8px 0;
            border: none;
            cursor: pointer;
            width: 100%;
            opacity: 0.9;
        }

        .registerbtn:hover {
            opacity: 1;
        }

        /* Add a blue text color to links */
        a {
            color: dodgerblue;
        }

        /* Set a grey background color and center the text of the "sign in" section */
        .signin {
            background-color: #f1f1f1;
            text-align: center;
        }
    </style>
</head>
        <body>
         <h1>Registo</h1>
            <p>Prencha o formulario para criar a sua conta de Blackjack</p>
                 <hr>

         <form action="<?=URL::toRoute('user/create')?>">
                         <div class="container">

                <label for="nome"><b>Nome Completo</b></label>
                <input type="text" value="<?=$user->nomecompleto?>" placeholder="Indique o seu nome completo" name = "nome" required>

                <label for="dnasc"><b>Data de Nascimento</b></label>
                <input type="text" value="<?=$user->datanasc?>" placeholder="Indique a sua data de nascimento" name = "datanasc" required>

                <label for="email"><b>Email</b></label>
                <input type="text" value="<?=$user->email?>" placeholder="Indique o seu email" name="email" required>

                <label for="username"><b>Username</b></label>
                <input type="text" value="<?=$user->username?>" placeholder="Indique o seu nome de utilizador" name="username" required>

                <label for="pwd"><b>Palavra Passe</b></label>
                <input type="password" value="<?=$user->pwd?>" placeholder="Coloque Palavra Passe" name="password" required>

                <button type="submit" class="registerbtn">Registar</button>
            </div>

            <div class="container signin">
                <p>Ja tens uma Conta? <a href="login">Entrar</a>.</p>
            </div>
        </form>
    </body>
</html>
