<?php

use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
$title = Data::get('title');
?>
<div>
<ol class="breadcrumb">
        <li><a href="<?=URL::toRoute('home/index')?>">Home</a></li>
        <li class="active"><?=$title?></li>
    </ol>

    <div class="row">

        <!-- Article main content -->
        <article class="col-md-8 maincontent">
            <header class="page-header">
                <h1 class="page-title"><?=$title?></h1>
            </header></div>
</div>