<footer id="footer" class="top-space">

    <div class="footer1">
        <div class="container">
            <div class="row">

                <div class="col-md-3 widget">
                    <h3 class="widget-title">Contact</h3>
                    <div class="widget-body">
                        <p>+351 244 300 800<br>
                            <a href="mailto:#">s.email@ipleiria.pt</a><br>
                            <br>
                            School of Technology and Management (ESTG)<br>
                            Polytechnic Institute of Leiria<br>
                            Morro do Lena, Campus 2<br>
                            2400 Leiria<br>
                            Portugal<br>
                        </p>
                    </div>
                </div>

                <div class="col-md-3 widget">
                    <h3 class="widget-title">Follow Us</h3>
                    <div class="widget-body">
                        <p class="follow-me-icons">
                            <a href=""><i class="fa fa-twitter fa-2"></i></a>
                            <a href=""><i class="fa fa-dribbble fa-2"></i></a>
                            <a href=""><i class="fa fa-github fa-2"></i></a>
                            <a href=""><i class="fa fa-facebook fa-2"></i></a>
                        </p>
                    </div>
                </div>

                <div class="col-md-6 widget">
                    <div class="widget-body">
                        <p>Technology is nothing. What's important is that you have a faith in people, that they're basically good and smart, and if you give them tools, they'll do wonderful things with them.</p>
                    </div>
                    <h3 class="widget-title">Steve Jobs</h3>
                </div>

            </div> <!-- /row of widgets -->
        </div>
    </div>

<div class="footer2">
    <div class="container">
        <div class="row">

            <div class="col-md-6 widget">
                <div class="widget-body">
                    <p class="simplenav">
                        <a href="#">Home</a> |
                        <a href="about.html">About</a> |
                        <a href="sidebar-right.html">Sidebar</a> |
                        <a href="contact.html">Contact</a> |
                        <b><a href="signup.html">Sign up</a></b>
                    </p>
                </div>
            </div>

            <div class="col-md-6 widget">
                <div class="widget-body">
                    <p class="text-right">
                        Copyright &copy; 2016-2017, Silvio Priem Mendes, PhD. <br> Site template by Sergey Pozhilov.
                    </p>
                </div>
            </div>

        </div> <!-- /row of widgets -->
    </div>
</div>

</footer>

<!-- JavaScript libs are placed at the end of the document so the pages load faster -->

<?php
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\Facades\DebugRenderer;
?>

<?=AssetBundler::js()?>

<script>hljs.initHighlightingOnLoad();</script>

</body>
</html>