<!DOCTYPE html>
<hmtl>
    <head>
        <style>
            .form {
                width: 500px;
                clear: both;
            }

            .form input {
                width: 100%;
                clear: both;
            }
        </style>
    </head>
    <body>
        <div class="form">
            <form action="webapp/model/CreateUserModel.php" method="post">
                Nome Completo: <input type="text" name="nome"><br/><br/>
                Data de Nascimento: <input type="text" name="dnasc"><br/><br/>
                Email: <input type="text" name="email"><br/><br/>
                Utilizador: <input type="text" name="username"><br/><br/>
                Password: <input type="password" name="pwd"><br/><br/>
                Tipo: <select name="usertype">
                        <option>Administrator</option>
                        <option>Player</option>
                      </select>
            </form>
        </div>
    </body>
</hmtl>